# Generated by Django 3.2.9 on 2022-06-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_article_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPageArticle',
        ),
    ]
