# Generated by Django 3.2.9 on 2022-06-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220626_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='first_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='first_photo',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_article',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_photo',
        ),
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='article/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.article')),
            ],
        ),
    ]
