# Generated by Django 3.2.9 on 2022-06-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default='workshops/default_workshops_photo.jpg', upload_to='workshops/'),
        ),
    ]
