# Generated by Django 3.2.6 on 2022-06-22 06:55

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('teaching_grade', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('form_url', models.URLField()),
                ('location', models.CharField(max_length=400)),
                ('material_password', models.CharField(blank=True, max_length=50, null=True)),
                ('lock', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='TTP/default_TTP_photo.jpg', upload_to='TTP/')),
                ('ttp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherteachingprogram.ttp')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_drive_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('ttp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherteachingprogram.ttp')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=400, null=True)),
                ('description', models.TextField(null=True)),
                ('ttp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherteachingprogram.ttp')),
            ],
        ),
    ]
