# Generated by Django 3.2.9 on 2022-07-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherteachingprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttp',
            name='post_photo',
            field=models.ImageField(default='TTP/default_TTP_photo.jpg', upload_to='TTP/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='TTP/'),
        ),
    ]
