# Generated by Django 3.2.9 on 2022-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='post_photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', upload_to='activity/'),
        ),
        migrations.AlterField(
            model_name='activityphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='activity/'),
        ),
    ]
