# Generated by Django 3.2.9 on 2022-06-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnwithyourkids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnwithyourkids',
            name='photo',
            field=models.ImageField(blank=True, default='default_photo.jpg', upload_to='learnwithyourkids/'),
        ),
    ]
